// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package com.palm.ice.ice;

// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _PrinterOperations
{
    boolean printPIceBean(PIceBean bean, Ice.Current __current);

    boolean printPIceMap(java.util.Map<java.lang.String, java.lang.String> map, Ice.Current __current);

    boolean printPIceBeanArray(PIceBean[] array, Ice.Current __current);
}
