// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package com.palm.ice.ice;

// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public final class PIceStrPrxHelper extends Ice.ObjectPrxHelperBase implements PIceStrPrx
{
    public static PIceStrPrx
    checkedCast(Ice.ObjectPrx __obj)
    {
        PIceStrPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (PIceStrPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA("::com::palm::ice::ice::PIceStr"))
                {
                    PIceStrPrxHelper __h = new PIceStrPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static PIceStrPrx
    checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        PIceStrPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (PIceStrPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA("::com::palm::ice::ice::PIceStr", __ctx))
                {
                    PIceStrPrxHelper __h = new PIceStrPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static PIceStrPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        PIceStrPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA("::com::palm::ice::ice::PIceStr"))
                {
                    PIceStrPrxHelper __h = new PIceStrPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static PIceStrPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        PIceStrPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA("::com::palm::ice::ice::PIceStr", __ctx))
                {
                    PIceStrPrxHelper __h = new PIceStrPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static PIceStrPrx
    uncheckedCast(Ice.ObjectPrx __obj)
    {
        PIceStrPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (PIceStrPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                PIceStrPrxHelper __h = new PIceStrPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static PIceStrPrx
    uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        PIceStrPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            PIceStrPrxHelper __h = new PIceStrPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    protected Ice._ObjectDelM
    __createDelegateM()
    {
        return new _PIceStrDelM();
    }

    protected Ice._ObjectDelD
    __createDelegateD()
    {
        return new _PIceStrDelD();
    }

    public static void
    __write(IceInternal.BasicStream __os, PIceStrPrx v)
    {
        __os.writeProxy(v);
    }

    public static PIceStrPrx
    __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            PIceStrPrxHelper result = new PIceStrPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }
}
