// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package com.palm.ice.ice;

// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public final class PIceBeanPrxHelper extends Ice.ObjectPrxHelperBase implements PIceBeanPrx
{
    public static PIceBeanPrx
    checkedCast(Ice.ObjectPrx __obj)
    {
        PIceBeanPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (PIceBeanPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA("::com::palm::ice::ice::PIceBean"))
                {
                    PIceBeanPrxHelper __h = new PIceBeanPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static PIceBeanPrx
    checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        PIceBeanPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (PIceBeanPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA("::com::palm::ice::ice::PIceBean", __ctx))
                {
                    PIceBeanPrxHelper __h = new PIceBeanPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static PIceBeanPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        PIceBeanPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA("::com::palm::ice::ice::PIceBean"))
                {
                    PIceBeanPrxHelper __h = new PIceBeanPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static PIceBeanPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        PIceBeanPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA("::com::palm::ice::ice::PIceBean", __ctx))
                {
                    PIceBeanPrxHelper __h = new PIceBeanPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static PIceBeanPrx
    uncheckedCast(Ice.ObjectPrx __obj)
    {
        PIceBeanPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (PIceBeanPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                PIceBeanPrxHelper __h = new PIceBeanPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static PIceBeanPrx
    uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        PIceBeanPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            PIceBeanPrxHelper __h = new PIceBeanPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    protected Ice._ObjectDelM
    __createDelegateM()
    {
        return new _PIceBeanDelM();
    }

    protected Ice._ObjectDelD
    __createDelegateD()
    {
        return new _PIceBeanDelD();
    }

    public static void
    __write(IceInternal.BasicStream __os, PIceBeanPrx v)
    {
        __os.writeProxy(v);
    }

    public static PIceBeanPrx
    __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            PIceBeanPrxHelper result = new PIceBeanPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }
}
