// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package com.palm.ice.ice;

// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface PrinterPrx extends Ice.ObjectPrx
{
    public boolean printPIceBean(PIceBean bean);

    public boolean printPIceBean(PIceBean bean, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_printPIceBean(PIceBean bean);

    public Ice.AsyncResult begin_printPIceBean(PIceBean bean, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_printPIceBean(PIceBean bean, Ice.Callback __cb);

    public Ice.AsyncResult begin_printPIceBean(PIceBean bean, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_printPIceBean(PIceBean bean, Callback_Printer_printPIceBean __cb);

    public Ice.AsyncResult begin_printPIceBean(PIceBean bean, java.util.Map<String, String> __ctx, Callback_Printer_printPIceBean __cb);

    public boolean end_printPIceBean(Ice.AsyncResult __result);

    public boolean printPIceMap(java.util.Map<java.lang.String, java.lang.String> map);

    public boolean printPIceMap(java.util.Map<java.lang.String, java.lang.String> map, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_printPIceMap(java.util.Map<java.lang.String, java.lang.String> map);

    public Ice.AsyncResult begin_printPIceMap(java.util.Map<java.lang.String, java.lang.String> map, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_printPIceMap(java.util.Map<java.lang.String, java.lang.String> map, Ice.Callback __cb);

    public Ice.AsyncResult begin_printPIceMap(java.util.Map<java.lang.String, java.lang.String> map, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_printPIceMap(java.util.Map<java.lang.String, java.lang.String> map, Callback_Printer_printPIceMap __cb);

    public Ice.AsyncResult begin_printPIceMap(java.util.Map<java.lang.String, java.lang.String> map, java.util.Map<String, String> __ctx, Callback_Printer_printPIceMap __cb);

    public boolean end_printPIceMap(Ice.AsyncResult __result);

    public boolean printPIceBeanArray(PIceBean[] array);

    public boolean printPIceBeanArray(PIceBean[] array, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_printPIceBeanArray(PIceBean[] array);

    public Ice.AsyncResult begin_printPIceBeanArray(PIceBean[] array, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_printPIceBeanArray(PIceBean[] array, Ice.Callback __cb);

    public Ice.AsyncResult begin_printPIceBeanArray(PIceBean[] array, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_printPIceBeanArray(PIceBean[] array, Callback_Printer_printPIceBeanArray __cb);

    public Ice.AsyncResult begin_printPIceBeanArray(PIceBean[] array, java.util.Map<String, String> __ctx, Callback_Printer_printPIceBeanArray __cb);

    public boolean end_printPIceBeanArray(Ice.AsyncResult __result);
}
